/*
 * Scryfall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace EdhTracker.Components;
public partial class AddGameDialog : IDisposable
{
    public void Dispose()
    {
        DataContext.Dispose();
    }
}