/*
 * Scryfall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines legal_status
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LegalStatus
    {
        /// <summary>
        /// Enum Legal for value: legal
        /// </summary>
        [EnumMember(Value = "legal")]
        Legal = 1,

        /// <summary>
        /// Enum NotLegal for value: not_legal
        /// </summary>
        [EnumMember(Value = "not_legal")]
        NotLegal = 2,

        /// <summary>
        /// Enum Restricted for value: restricted
        /// </summary>
        [EnumMember(Value = "restricted")]
        Restricted = 3,

        /// <summary>
        /// Enum Banned for value: banned
        /// </summary>
        [EnumMember(Value = "banned")]
        Banned = 4
    }

}
